### ISSUE TITLE
About implementation

### ISSUE THREAD

**Issue by dongqian0206** [yjxiao/textvae#1]
Hi Yijun, Thanks for providing this code. I am trying to implement VAE-RNN based on your code. 

(1) You used linear annealing to alleviate posterior collapse issue. Is this a common way? Actually, I tried different ways (sigmoid annealing) but always failed. Does it mean that different datasets should be based on different annealing strategies (you used start=2k and duration=40k)?

(2) For the decoder RNN part, you did not concatenate the latent code (z) and hidden state as the input to the RNN at each time step. Am I right?

(3) Did you try to fine-tune models with different parameters or these default parameter settings are best?

Looking forward to your replay. Thanks.

Dong Qian

**Comment by yjxiao** [comment]
Hi @dongqian0206, thanks for your interest!

(1) I've seen people using different scheduling function. Linear annealing is a version I used for another model [https://github.com/yjxiao/TopicGeneratingVAE](https://github.com/yjxiao/TopicGeneratingVAE). I'm not very sure this works well for vanilla VAE

(2) That's correct. The latent code is not fed into the RNN decoder at each time step.

(3) I have not experimenting with the vanilla VAE. This repo is for demo purpose. But I'm thinking about updating this repo as it is kind of messy and outdated.
